### PR TITLE
remove JMeter plugin incompatible with SQ 5.6.2

### PR DESCRIPTION
**Pull request by m4m51m**

### CODE REVIEW

**Comment by anton-kasperovich** [comment]
@m4m51m could you please provide some comments, how exactly it's incompatible? where the issue? i would like to understand, as previously we've accepted this plugin as part of other PR, so to not make such mistakes again. Thank you in advance!

**Comment by uyenle5796** [comment]
@anton-kasperovich Hi Anton, I also created a PR on this [](url)https://github.com/Accenture/adop-sonar/pull/17 few days ago without aware that there's already a PR on this.
 
plugin JMeter v3.0 is outdated for Sonarqube 5.6+ (as shown here: http://www.sonarplugins.com/jmeter), hence causing our Sonar builds to fail.

This has been tested locally.

**Comment by deors** [comment]
Hi @anton-kasperovich , I think your questions is still unanswered, so let me try to explain why this is relevant. We added JMeter plug-in in a previous PR but it was back when we were on SonarQube 5.1.x platform. Since the release of SonarQube 5.6.x, however, there are changes in the API that makes JMeter plug-in not compatible, and hence it does not work. Since we have already bumped SQ version to 5.6.x, we shall remove JMeter plug-in. As a rule of thumb for future SQ version updates, we shall be looking as well to the current list of integrated plug-ins, to ensure we are also updating version plug-ins or, as is this case, removing older, no longer maintained, non-compatible plug-ins. Hope that helps to clarify.

**Comment by SachinKSingh28** [comment]
I have tested this PR with java cartridge successfully. Removing the incompatible jmeter plugin fixes the problem with sonar analysis jobs as well. Hoping that soon we will have a compatible jmeter plugin which we can introduce again.

**Pull request merged**
