### PR TITLE
Upgrade SonarQube base image version on v4.5.6

### PR DESCRIPTION
**Pull request by anton-kasperovich**
Upgrade will fix at least one issue related to Complexity broken charts.

They also change version of Java ( java:openjdk-8u45-jre ) and added security checks.

I checked on latest version of ADOP, everything looks working:

screenshot 2016-03-25 17 10 43

### CODE REVIEW

**Comment by nickdgriffin** [comment]
LGTM.

Going to merge this in so that Docker Hub builds the latest version, once that's available can you verify it works please and once confirmed I'll tag the new release ready for the Compose file?

Thanks!

**Comment by anton-kasperovich** [comment]
@nickdgriffin tested with the latest version of Compose file and latest tag of ADOP Sonar image ( commit cbc23899640b7a6ba7bb12398dab6987cfd9ea87 ) :

```
-  image: accenture/adop-sonar:0.1.0
+  image: accenture/adop-sonar
```

Everything works fine.

**Comment by nickdgriffin** [comment]
Great, thanks for testing!

I've created the release, it should appear in Docker Hub relatively soon. Can you submit a PR on adop-docker-compose once the image is available please?

**Comment by anton-kasperovich** [comment]
done

**Pull request merged**
