### PR TITLE
Add  core java blueprint plugins to adop-sonar

### PR DESCRIPTION
**Pull request by restalion**
See below plugins added:
- sonar-checkstyle-plugin-2.3.jar
- sonar-css-plugin-1.2.jar
- sonar-jmeter-plugin-0.3.jar
- sonar-motion-chart-plugin-1.7.jar
- sonar-pitest-plugin-0.6.jar
- sonar-pmd-plugin-2.4.1.jar
- sonar-scm-stats-plugin-0.3.1.jar
- sonar-timeline-plugin-1.4.jar
- sonar-web-plugin-2.4.jar
- sonar-xml-plugin-1.3.jar

### CODE REVIEW

**Comment by deors** [comment]
hi @nickdgriffin, any plans for merging this one into master, publish the new image, and hopefully upgrade docker-compose to use the latest SonarQube plug-ins?

**Comment by anton-kasperovich** [comment]
@restalion could you please squash commits into one, also, could you please remove "Add .gitattributes file to avoid error when clone project in Windows" commit "1aa7b56" from this pull request, thank you in advance!

Did you also tested it with updated plugins and current version of ADOP SonarQube Docker image?

**Comment by anton-kasperovich** [comment]
@nickdgriffin tested latest tag of SonarQube image (SonarQube 5.1.2 version which you already accepted) with these plugins and Java Cartridge - everything looks good. 👍

**Comment by restalion** [comment]
@anton-kasperovich I've just did squash commits into a single one, .gitattributes commit is also removed.
Regards,

**Comment by nickdgriffin** [comment]
LGTM. I'll create a new release.

**Pull request merged**
